server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/netflix_auth
    username: postgres
    password: arpon007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: "NetflixCloneSecretKeyForJwtTokenGenerationShouldBeLongEnough"
      expiration: 86400000
admin:
  email: admin@netflix.com
  password: admin
  fullname: Admin User

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://localhost:8080"
